### PR TITLE
add running to typescript definition

### PR DESCRIPTION
**Pull request by Uzlopak**

### CODE REVIEW

**Comment by Uzlopak** [comment]
When running the jsdoc typechecking with typescript in vscode on avvio, it is reporting that running is not defined.

image

**Comment by mcollina** [comment]
Can you add it to example.ts?

**Comment by Uzlopak** [comment]
I originally wanted to add it, but example.ts seemed to be some working code example, so I hesitated. 

Will add.

**Comment by Uzlopak** [comment]
done.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Uzlopak** [comment]
@mcollina 
ptal

**Pull request merged**
